# Site settings
title: MIT Sloan Application
email: cthomas.london@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Supporting Chris Ellis Thomas' application to the MBA program at the
  MIT Sloan School of Management
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mitsloan.cellist.co" # the base hostname & protocol for your site
twitter_username: cellist_co
github_username:  cellistlondon

# Build settings
markdown: kramdown
exclude: ["node_modules", "less", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock"]
